name: docker

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- uses: mxschmitt/action-tmate@v3
    - name: composer update
      run: |
        composer update
    - name: prepare config
      run: |
        cp config.ini.sample config.ini
        mkdir MY_REPORTS_DIR MY_TEMP_DIR
    - name: test
      run: |
        php -f index.php _testFiles 1
