name: docker

on:
  release: ~
  workflow_dispatch: ~

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        docker build -t acdhch/arche-filechecker:latest --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" .
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: docker push acdhch/arche-filechecker:latest
    - name: build ACDH
      run: |
        echo "RUN apt update && apt install -y vim && apt clean" >> Dockerfile
        docker build -t acdhch/arche-filechecker:acdh --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" .
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: docker push acdhch/arche-filechecker:acdh
