name: docker

on:
  push: ~

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- uses: mxschmitt/action-tmate@v3
    - name: cache AV database
      id: avdb
      uses: actions/cache@v3
      with:
        path: ~/.cvdupdate
        key: constant
    - name: refresh AV database
      run: python3 -m pip install --user cvdupdate && cvd update && echo "foo"
    - name: composer
      run: composer update --no-dev -o 
    - name: test
      # the filechecker should have non-zero error code
      run: |
        RET=1
        mkdir reports && bin/arche-filechecker --tmpDir /tmp --reportDir reports _testFiles 3 || RET=0
        exit $RET

