name: test

on:
  push: ~

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- uses: mxschmitt/action-tmate@v3
    - name: composer
      run: composer update
    - name: test
      run: |
        vendor/bin/phpunit
        RET=1
        mkdir -p tests/reports && bin/arche-filechecker --tmpDir /tmp tests/data/ tests/reports/ || RET=0
        exit $RET

