name: test

on:
  push: ~

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: composer
      run: composer update
    #- uses: mxschmitt/action-tmate@v3
    - name: phpstan
      run:
        vendor/bin/phpstan analyze -l 6 src bin/arche-filechecker tests
    - name: unit tests
      run: |
        mkdir -p build/logs
        # same mount path in host and container so that coveralls can match files in the host afterwords
        docker run -t --rm -v `pwd`:`pwd` -w `pwd` -e LC_ALL=C.utf8 -e LANG=C.utf8 -e XDEBUG_MODE=coverage --entrypoint `pwd`/vendor/bin/phpunit acdhch/arche-ingest
    - name: integration tests
      run: |
        RET=1
        docker run -t --rm -v `pwd`:/mnt --entrypoint /mnt/bin/arche-filechecker acdhch/arche-ingest /mnt/tests/data/ /mnt/tests/reports/ || RET=0
        exit $RET
    - name: coveralls
      run: |
        export COVERALLS_RUN_LOCALLY=1
        export COVERALLS_REPO_TOKEN=${{ secrets.coverallsToken }}
        rm -fR composer.json composer.lock vendor
        composer require php-coveralls/php-coveralls
        php vendor/bin/php-coveralls -v

