name: docker

on:
  push: ~

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- uses: mxschmitt/action-tmate@v3
    - name: cache AV database
      id: avdb
      uses: actions/cache@v3
      with:
        path: .cvdupdate
        key: constant
    - name: refresh AV database
      run: python3 -m pip install --user cvdupdate && cvd update
    - name: test
      run: |
        mkdir reports
        bin/arche-filechecker --tmpDir /tmp --reportsDir reports _testFiles 3

