name: test

on:
  push: ~

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- uses: mxschmitt/action-tmate@v3
    - name: composer
      run: composer update
    - name: test
      run: |
        docker run -t --rm -v `pwd`:/mnt --entrypoint /mnt/vendor/bin/phpunit acdhch/arche-ingest
        RET=1
        docker run -t --rm -v `pwd`:/mnt --entrypoint /mnt/bin/arche-filechecker acdhch/arche-ingest /mnt/tests/data/ /mnt/tests/reports/ || RET=0
        exit $RET

